pipeline{
    agent any
    
    stages{
        stage('Inicial')
        {
            steps
			{
                echo 'Teste de pepilene'
            }
        }
		 stage('Build')
        {
            steps
			{
                bat "dotnet build --project jenkins --configuration Release"
            }
        }
         stage('Build Test')
        {
            steps
			{
                bat "dotnet build --project jenkinsAPIteste --configuration Release"
            }
        }
    }
 }
 